package Lab;

import java.io.IOException;
import javax.swing.JOptionPane;

public class settingsNormalWIN extends javax.swing.JFrame {
    boolean register=false;
    boolean modify= false;
    boolean delete=false;

    /**
     * Creates new form settingsNormalWIN
     */
    public settingsNormalWIN() {
        initComponents();
        this.setLocationRelativeTo(null);
        setEverything();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        settingsPAN = new javax.swing.JPanel();
        usernameLABEL = new javax.swing.JLabel();
        usernameFIELD = new javax.swing.JTextField();
        tipoLABEL = new javax.swing.JLabel();
        tipoBox = new javax.swing.JComboBox<>();
        BTN = new javax.swing.JButton();
        edadLABEL = new javax.swing.JLabel();
        edadBox = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        settingsPAN.setBackground(new java.awt.Color(0, 0, 51));

        usernameLABEL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        usernameLABEL.setForeground(new java.awt.Color(255, 255, 255));
        usernameLABEL.setText("Username:");

        tipoLABEL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tipoLABEL.setForeground(new java.awt.Color(255, 255, 255));
        tipoLABEL.setText("TIpo:");

        tipoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        BTN.setBackground(new java.awt.Color(255, 255, 255));
        BTN.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BTN.setForeground(new java.awt.Color(0, 0, 51));
        BTN.setText("Register");
        BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNActionPerformed(evt);
            }
        });

        edadLABEL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        edadLABEL.setForeground(new java.awt.Color(255, 255, 255));
        edadLABEL.setText("Edad:");

        edadBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout settingsPANLayout = new javax.swing.GroupLayout(settingsPAN);
        settingsPAN.setLayout(settingsPANLayout);
        settingsPANLayout.setHorizontalGroup(
            settingsPANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPANLayout.createSequentialGroup()
                .addGroup(settingsPANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(settingsPANLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(settingsPANLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(settingsPANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(settingsPANLayout.createSequentialGroup()
                                .addComponent(edadLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(edadBox, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(settingsPANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tipoBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(settingsPANLayout.createSequentialGroup()
                                    .addComponent(usernameLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(usernameFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(tipoLABEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        settingsPANLayout.setVerticalGroup(
            settingsPANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPANLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(settingsPANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(settingsPANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edadLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edadBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(tipoLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tipoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        jButton4.setText("Home Page");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton1)
                                .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(settingsPAN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(settingsPAN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        register=true;
        modify=false;
        delete=false;
        Action();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        register=false;
        modify=true;
        delete=false;
        Action();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        register=false;
        modify=false;
        delete=true;
        Action();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new homeNomralWIN().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNActionPerformed
        if (register) { //para registrar
        String username = usernameFIELD.getText();
        String tipoUsuario = (String) tipoBox.getSelectedItem();
        int edad = Integer.parseInt((String) edadBox.getSelectedItem());

        try {
            Steam steam = new Steam();
            steam.addPlayer(username, edad, tipoUsuario);
            JOptionPane.showMessageDialog(null, "¡Jugador registrado exitosamente!");
        } catch (IOException e) {
            
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al registrar el jugador. Por favor, inténtalo de nuevo.");
        }
    } else if (modify) { // para modificar
        String username = usernameFIELD.getText();
        String tipoUsuario = (String) tipoBox.getSelectedItem();
        int edad = Integer.parseInt((String) edadBox.getSelectedItem());

        
        try {
            Steam steam = new Steam(); 
            steam.modifyPlayer(username, edad, tipoUsuario);
            JOptionPane.showMessageDialog(null, "¡Jugador modificado exitosamente!");
        } catch (IOException e) {
            
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al modificar el jugador. Por favor, inténtalo de nuevo.");
        }
    } else if (delete) { // para borrar
        // Lógica para eliminar un usuario
    }
    }//GEN-LAST:event_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(settingsNormalWIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(settingsNormalWIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(settingsNormalWIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(settingsNormalWIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new settingsNormalWIN().setVisible(true);
            }
        });
    }
    
    void setEverything(){
        setBox();
        setPanel();
    }
    
    void setBox(){
        tipoBox.removeAllItems();
        tipoBox.addItem("Normal");
        tipoBox.addItem("Admin");
        
        edadBox.removeAllItems();
        for(int i=1; i<=100; i++){
            String age=String.valueOf(i);
            edadBox.addItem(age);
        }
    }
    
    void setPanel(){
        usernameFIELD.setVisible(false);
            usernameLABEL.setVisible(false);
            tipoBox.setVisible(false);
            tipoLABEL.setText("Welcome to settings");
            BTN.setVisible(false);
            edadBox.setVisible(false);
            edadLABEL.setVisible(false);
    }
    
    void Action(){
        if(delete==true){
            usernameFIELD.setVisible(false);
            usernameLABEL.setVisible(false);
            tipoBox.setVisible(false);
            tipoLABEL.setText("Eliminar cuenta?");
            BTN.setText("Delete");
            BTN.setVisible(true);
            edadBox.setVisible(false);
            edadLABEL.setVisible(false);
        }else if(modify==true){
            usernameFIELD.setVisible(true);
            usernameLABEL.setVisible(true);
            tipoBox.setVisible(true);
            tipoLABEL.setText("Tipo");
            BTN.setText("Modify");
            BTN.setVisible(true);
            edadBox.setVisible(true);
            edadLABEL.setVisible(true);
        }else if(register==true){
            usernameFIELD.setVisible(true);
            usernameLABEL.setVisible(true);
            tipoBox.setVisible(true);
            tipoLABEL.setText("Tipo");
            BTN.setText("Register");
            BTN.setVisible(true);
            edadBox.setVisible(true);
            edadLABEL.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN;
    private javax.swing.JComboBox<String> edadBox;
    private javax.swing.JLabel edadLABEL;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel settingsPAN;
    private javax.swing.JComboBox<String> tipoBox;
    private javax.swing.JLabel tipoLABEL;
    private javax.swing.JTextField usernameFIELD;
    private javax.swing.JLabel usernameLABEL;
    // End of variables declaration//GEN-END:variables
}
